// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeInput: typeof import('./src/components/TimeInput.vue')['default']
    TimePicked: typeof import('./src/components/TimePicked.vue')['default']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    TimePointer: typeof import('./src/components/TimePointer.vue')['default']
  }
}
