// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Lecture: typeof import('./src/components/Lecture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeInput: typeof import('./src/components/TimeInput.vue')['default']
    TimePointer: typeof import('./src/components/TimePointer.vue')['default']
    Warning: typeof import('./src/components/Warning.vue')['default']
  }
}
